name: Main

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install packages
        run: npm install --no-dev
      - name: Build
        run: npm run build
      - name: Compress archive
        run: tar cfvz xhprof-ui-js_{{ github.ref }}.tar.gz ./build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: xhprof-ui-js_{{ github.ref }}.tar.gz
